version: 2
updates:
- package-ecosystem: npm
  directory: /
  schedule:
    interval: daily
    time: '22:00'
  open-pull-requests-limit: 5
  labels:
  - dependencies
  - security
  - nodejs
  commit-message:
    prefix: chore
    include: scope
  versioning-strategy: increase-if-necessary
