receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"

exporters:
  otlphttp/langfuse:
    endpoint: ${LANGFUSE_OTLP_ENDPOINT}
    headers:
      Authorization: ${LANGFUSE_AUTH_HEADER}
    tls:
      insecure: true

  debug:
    verbosity: detailed

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlphttp/langfuse, debug]